# SwiftLint configuration for BCryptSwift

# Paths to include
included:
  - BCryptSwift/Classes
  - Example/Tests

# Paths to exclude
excluded:
  - Pods
  - .build
  - Package.swift
  - Example/Pods
  - "*/Generated"

# Rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - lower_acl_than_parent
  - modifier_order
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - sorted_first_last
  - static_operator
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

disabled_rules:
  - todo
  - fixme
  - line_length
  - type_body_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - nesting
  - file_header
  - trailing_whitespace
  - identifier_name
  - force_cast
  - force_try
  - large_tuple
  - type_name
  - trailing_comma
  - vertical_whitespace
  - redundant_discardable_let
  - unneeded_override

# Rule configurations
function_parameter_count:
  warning: 8
  error: 10

# Reporter type
reporter: "xcode"