name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]
  release:
    types: [published]

env:
  SWIFT_VERSION: "5.9"

jobs:
  test-spm:
    name: Test (SPM)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-13
            xcode: '15.0'
          - os: macos-14
            xcode: '15.2'
          - os: macos-latest
            xcode: 'latest'
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
      
    - name: Swift version
      run: swift --version
      
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v --enable-code-coverage
      
    - name: Generate coverage report
      run: |
        xcrun llvm-cov export \
          .build/debug/BCryptSwiftPackageTests.xctest/Contents/MacOS/BCryptSwiftPackageTests \
          -instr-profile .build/debug/codecov/default.profdata \
          -format lcov > coverage.lcov
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.lcov
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
        verbose: true

  test-cocoapods:
    name: Test (CocoaPods)
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
      
    - name: Install CocoaPods
      run: gem install cocoapods
      
    - name: Pod install
      run: |
        cd Example
        pod install
        
    - name: Build and test
      run: |
        cd Example
        xcodebuild test \
          -workspace BCryptSwift.xcworkspace \
          -scheme BCryptSwift-Example \
          -destination 'platform=iOS Simulator,OS=latest,name=iPhone 15' \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO


  lint:
    name: SwiftLint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v4
    
    - name: Run security audit
      uses: actions/dependency-review-action@v4
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

  build-docs:
    name: Build Documentation
    runs-on: macos-13
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
      
    - name: Install Jazzy
      run: gem install jazzy
      
    - name: Build Swift Package
      run: swift build
      
    - name: Generate documentation
      run: jazzy --output docs
          
    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/

  release:
    name: Release
    runs-on: macos-13
    needs: [test-spm, test-cocoapods, lint]
    if: github.event_name == 'release'
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
      
    - name: Install CocoaPods
      run: gem install cocoapods
      
    - name: Update version in podspec
      run: |
        VERSION=${{ github.event.release.tag_name }}
        VERSION=${VERSION#v}  # Remove 'v' prefix if present
        sed -i '' "s/s.version.*=.*/s.version          = '$VERSION'/" WisetailBCryptSwift.podspec
        
    - name: Validate podspec
      run: pod lib lint WisetailBCryptSwift.podspec --allow-warnings
      
    - name: Deploy to CocoaPods Trunk
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push WisetailBCryptSwift.podspec --allow-warnings
        
    - name: Update Package.swift version tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add WisetailBCryptSwift.podspec
        git commit -m "Update podspec version to ${{ github.event.release.tag_name }}"
        git push